-- Target-state reference only. Not executed by this repository.
-- Synthetic data only. Review before use. No credentials required.

CREATE DATABASE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.RAW;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.STAGING;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.GOVERNANCE;
