-- Target-state reference only. Not executed by this repository.
-- Synthetic data only. Review before use. No credentials required.

CREATE FILE FORMAT IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.RAW.HLA_CANONICAL_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  ESCAPE_UNENCLOSED_FIELD = NONE
  NULL_IF = ('')
  ENCODING = 'UTF8'
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE FILE FORMAT IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.RAW.HLA_CANONICAL_PARQUET
  TYPE = PARQUET
  USE_LOGICAL_TYPE = TRUE;
