-- Target-state reference only. Not executed by this repository.
-- Synthetic data only. Review before use. No credentials required.

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.RAW.RAW_CLINICAL_DOCUMENTS (
  DOCUMENT_ID VARCHAR NOT NULL,
  SYNTHETIC_SUBJECT_ID VARCHAR NOT NULL,
  SYNTHETIC_ENCOUNTER_ID VARCHAR NOT NULL,
  DOCUMENT_TYPE VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL,
  DATA_CLASSIFICATION VARCHAR NOT NULL,
  DOCUMENT_TEXT VARCHAR NOT NULL,
  DOCUMENT_CREATED_AT TIMESTAMP_TZ NOT NULL,
  ENCOUNTER_STARTED_AT TIMESTAMP_TZ NOT NULL,
  ENCOUNTER_ENDED_AT TIMESTAMP_TZ NOT NULL,
  INGESTION_RUN_ID VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.RAW.RAW_DOCUMENT_ANNOTATIONS (
  ANNOTATION_ID VARCHAR NOT NULL,
  DOCUMENT_ID VARCHAR NOT NULL,
  ANNOTATION_TYPE VARCHAR NOT NULL,
  LABEL VARCHAR NOT NULL,
  VALUE VARCHAR NOT NULL,
  NORMALISED_VALUE VARCHAR NOT NULL,
  START_OFFSET NUMBER,
  END_OFFSET NUMBER,
  INGESTION_RUN_ID VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.STAGING.STG_CLINICAL_DOCUMENTS
LIKE HEALTHCARE_LANGUAGE_AI.RAW.RAW_CLINICAL_DOCUMENTS;

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.STAGING.STG_DOCUMENT_ANNOTATIONS
LIKE HEALTHCARE_LANGUAGE_AI.RAW.RAW_DOCUMENT_ANNOTATIONS;

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.GOVERNANCE.INGESTION_RUNS (
  INGESTION_RUN_ID VARCHAR NOT NULL,
  RUN_STATUS VARCHAR NOT NULL,
  SYNTHETIC_DATA_ONLY BOOLEAN NOT NULL,
  CLINICAL_USE_PROHIBITED BOOLEAN NOT NULL,
  EVIDENCE VARIANT
);

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.GOVERNANCE.INGESTION_RECONCILIATION (
  INGESTION_RUN_ID VARCHAR NOT NULL,
  METRIC_NAME VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  SEVERITY VARCHAR NOT NULL,
  EVIDENCE VARIANT
);

CREATE TABLE IF NOT EXISTS HEALTHCARE_LANGUAGE_AI.GOVERNANCE.QUARANTINED_RECORDS (
  PAYLOAD_CHECKSUM VARCHAR NOT NULL,
  ERROR_CODE VARCHAR NOT NULL,
  ERROR_CATEGORY VARCHAR NOT NULL,
  QUARANTINE_TIMESTAMP TIMESTAMP_TZ NOT NULL,
  EVIDENCE VARIANT
);
