-- Target-state reference only. Not executed by this repository.
-- Synthetic data only. Review before use. No credentials required.

CREATE OR REPLACE VIEW HEALTHCARE_LANGUAGE_AI.STAGING.V_DOCUMENT_COUNTS AS
SELECT DOCUMENT_TYPE, COUNT(*) AS DOCUMENT_COUNT
FROM HEALTHCARE_LANGUAGE_AI.STAGING.STG_CLINICAL_DOCUMENTS
GROUP BY DOCUMENT_TYPE;

CREATE OR REPLACE VIEW HEALTHCARE_LANGUAGE_AI.STAGING.V_ANNOTATION_LABEL_COUNTS AS
SELECT LABEL, COUNT(*) AS ANNOTATION_COUNT
FROM HEALTHCARE_LANGUAGE_AI.STAGING.STG_DOCUMENT_ANNOTATIONS
GROUP BY LABEL;
