-- Target-state reference only. Not executed by this repository.
-- Synthetic data only. Review before use. No credentials required.
-- Do not use ACCOUNTADMIN for routine ownership in this design.

CREATE ROLE IF NOT EXISTS HLA_PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS HLA_INGESTION_ROLE;
CREATE ROLE IF NOT EXISTS HLA_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS HLA_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS HLA_READONLY_ROLE;

GRANT ROLE HLA_READONLY_ROLE TO ROLE HLA_ANALYST_ROLE;
GRANT ROLE HLA_ANALYST_ROLE TO ROLE HLA_TRANSFORM_ROLE;
GRANT ROLE HLA_TRANSFORM_ROLE TO ROLE HLA_PLATFORM_ADMIN;
GRANT ROLE HLA_INGESTION_ROLE TO ROLE HLA_PLATFORM_ADMIN;

GRANT USAGE ON DATABASE HEALTHCARE_LANGUAGE_AI TO ROLE HLA_READONLY_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEALTHCARE_LANGUAGE_AI TO ROLE HLA_READONLY_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE HEALTHCARE_LANGUAGE_AI TO ROLE HLA_READONLY_ROLE;
GRANT INSERT ON SCHEMA HEALTHCARE_LANGUAGE_AI.RAW TO ROLE HLA_INGESTION_ROLE;
GRANT INSERT ON SCHEMA HEALTHCARE_LANGUAGE_AI.GOVERNANCE TO ROLE HLA_INGESTION_ROLE;
