-- Target-state reference only. Not executed by this repository.
-- Synthetic data only. Review before use. No credentials required.

SELECT COUNT(*) AS DOCUMENT_COUNT
FROM HEALTHCARE_LANGUAGE_AI.RAW.RAW_CLINICAL_DOCUMENTS;

SELECT COUNT(*) AS ANNOTATION_COUNT
FROM HEALTHCARE_LANGUAGE_AI.RAW.RAW_DOCUMENT_ANNOTATIONS;

SELECT COUNT(*) AS ORPHAN_ANNOTATIONS
FROM HEALTHCARE_LANGUAGE_AI.RAW.RAW_DOCUMENT_ANNOTATIONS A
LEFT JOIN HEALTHCARE_LANGUAGE_AI.RAW.RAW_CLINICAL_DOCUMENTS D
  ON A.DOCUMENT_ID = D.DOCUMENT_ID
WHERE D.DOCUMENT_ID IS NULL;
